### PR TITLE
New multiqubit gate

### PR DESCRIPTION
**Pull request by GiggleLiu**
```julia
julia> c1 = chain(5, [ContinuousBlockMarker(put(5, (2,3)=>SWAP), "SWAP"), 
  ContinuousBlockMarker(put(5, 2=>I2), "id"), put(5, 2=>ContinuousBlockMarker(X, "X")),
  control(5, (5,3), (2,4,1)=>ContinuousBlockMarker(put(3, (1,3)=>SWAP), "SWAP"))])

julia> vizcircuit(c1)
```

image

On the other side, if you try to visualize the following gate, you will get an error.
```julia
    c2 = chain(5, [ContinuousBlockMarker(put(5, (2,3)=>SWAP), "SWAP"), ContinuousBlockMarker(put(5, 2=>I2), "id"), put(5, 2=>ContinuousBlockMarker(X, "X")), control(5, (5,3), (2,4,1)=>ContinuousBlockMarker(put(3, (1,2)=>SWAP), "SWAP"))])
```

### CODE REVIEW

**Comment by VarLad** [comment]
Great！I hope this gets simplified in the future！Thank you taking the time @GiggleLiu 😄

**Comment by GiggleLiu** [comment]
Yeah, but we need a proposal about how to make it simpler. I do not want to insert a name field to the ChainBlock. If you have any interesting idea, feel free to open an issue.

**Comment by Roger-luo** [comment]
Can you explain why we need an extra block node? It seems to me a method like nameof is sufficient for determining the name of a block.

**Comment by VarLad** [comment]
@Roger-luo Sounds great to me！🙂

**Comment by GiggleLiu** [comment]
> Can you explain why we need an extra block node? It seems to me a method like nameof is sufficient for determining the name of a block.

But the name is not static.

**Comment by Roger-luo** [comment]
I think there at least should be a default fallback name for primitive gates, or why `ContinuousBlockMarker(put(5, 2=>I2), "id")` is not displayed if the user specified it manually? I don't think we should hide any block that user has specified explicitly. we can let `ContinuousBlockMarker` to change the default name, so the code will look less noisy, e.g

```julia
c1 = chain(5, [ContinuousBlockMarker(put(5, (2,3)=>SWAP), "my custom name for SWAP"), 
  ContinuousBlockMarker(put(5, 2=>I2), "explicit id"), put(5, 2=>X),
  control(5, (5,3), put(3, (1,3)=>SWAP))])
```

where the X gate will be using a default name `X`, and the block `I2` should be displayed explicitly since the user has specified a name for it explicitly (or why should we allow the user to do so?)

on the other hand, what does the word `Continuous` stands for in `ContinuousBlockMarker`? can we make it shorter to be just `BlockName` or something like that?

**Comment by GiggleLiu** [comment]
I2 is not shown because we use `occpied_locs` does not count it. Maybe instead of
```julia
ContinuousBlockMarker(put(5, (2,3)=>SWAP))
```

We should use
```julia
put(5, (2,3)=>put(5, (2,3)=>LabeledBlock(SWAP, "SWAP"))
```

**Comment by VarLad** [comment]
Whats the problem with,

```
​put​(​5​, (​2​,​3​)​=>​LabeledBlock​(SWAP, ​"​SWAP​"​))
```

**Comment by VarLad** [comment]
Also, if you could shorten it or make a "lazy" version of LabeledBlock

​` put​(​5​, (​2​,​3​)​=>​label(SWAP, ​"​SWAP​"​)) `


This looks perfect！
Can this be done？

**Comment by GiggleLiu** [comment]
> Whats the problem with,
> 
> ```
> ​put​(​5​, (​2​,​3​)​=>​LabeledBlock​(SWAP, ​"​SWAP​"​))
> ```

```julia
control(5, (5,3), (2,4,1)=>ContinuousBlockMarker(put(3, (1,3)=>SWAP), "SWAP"))
```

**Comment by GiggleLiu** [comment]
> Whats the problem with,
> 
> ```
> ​put​(​5​, (​2​,​3​)​=>​LabeledBlock​(SWAP, ​"​SWAP​"​))
> ```

It can not handle the following gate

```julia
ContinuousBlockMarker(chain(5, put(5, 2=>X), put(5, 3=>X)), "XX")
```

Instead, one has to change the circuit to
```julia
chain(5, put(5, (2, 3)=>label(kron(X, X), "XX")))
```

It is not a big issue, the later looks more intuitive.

**Comment by VarLad** [comment]
> Instead, one has to change the circuit to
> ```julia
> chain(5, put(5, (2, 3)=>label(kron(X, X), "XX")))
> ```
> 
> It is not a big issue, the later looks more intuitive.

What about

```
​circuit = chain​(​5​, ​ put​(​2​=>​X), ​put​(​3​=>​X))
XX = chain(5, put(1:5 => label(circuit, "XX"))
```

**Comment by VarLad** [comment]
Just one more thing！
If a given DaggeredBlock has a name/label assigned to it, can you plot it as name/label† in a rectangular box？
This might be the best solution for plotting Daggered Block, other than ` ' `

**Comment by GiggleLiu** [comment]
You mean this?

```julia
chain(5, [put(5, (2,3)=>label(SWAP, "SWAP")'), put(5, 2=>label(I2, "id")), put(5, 2=>label(X, "X")), control(5, (5,3), (2,4,1)=>put(3, (1,3)=>label(SWAP, "SWAP")))]) |> vizcircuit
```

image

**Comment by GiggleLiu** [comment]
@Roger-luo good now?

**Comment by Roger-luo** [comment]
LGTM

**Comment by GiggleLiu** [comment]
We can also use ishermitian to detect whether the content in a labeled block is hermitian, so that we can save a dagger in this case (because the SWAP gate is hermitian).

Which is better?

**Comment by VarLad** [comment]
Great！Sounds good to me！
Thanks a lot for taking the time again😄

**Comment by GiggleLiu** [comment]
> Great！Sounds good to me！
> Thanks a lot for taking the time again

Thank you too for providing practical using cases to guide the design of visualization.

@Roger-luo , I think this PR is ready to merge.

**Comment by Roger-luo** [comment]
I think we should just follow whatever user is written - we shouldn't perform optimization at this level.

**Pull request merged**
