### PR TITLE
Add vega plot backend

### PR DESCRIPTION
**Pull request by ChenZhao44**
I changed the plotting backend of ZXCalculus to Compose.jl and Vega.jl.
Version of ZXCalculus.jl should be >= 0.4.4

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Why do you support Vega backend, it looks like a dead project: https://github.com/johnmyleswhite/Vega.jl
The latest update is 4 years ago.

**Comment by ChenZhao44** [comment]
@GiggleLiu I want an interactive backend. And I found it still works.

**Comment by ChenZhao44** [comment]
@GiggleLiu The latest Vega.jl is moved to https://github.com/queryverse/Vega.jl

**Comment by Roger-luo** [comment]
I think ZX part looks good to me - I don't aim for a very stable visualization for ZX/Quon at the moment anyway.

Vega is a ggplot like standard, it doesn't matter what backend is, I think it's useful to generate that standard.

**Pull request merged**
