### PR TITLE
Add instructions for changing plot attributes 

### PR DESCRIPTION
**Pull request by VarLad**

### CODE REVIEW

**Comment by GiggleLiu** [comment]
Hi, Varlad. Thank you very much for the PR, I really like your examples. There are two things these examples can improve
1. I wish it can be a part of example 1, like a subsection, instead of a seperate section after ZX-plot. Because these theme changes does not apply for ZX-calculus, we should try our best to avoid misleading people.
2. show one example instead of two, because now they have many overlaps

**Comment by VarLad** [comment]
Regarding two examples! 
Breaking into two smaller examples makes it easier to _highlight_ I thought?
Although if you still want to, I can remove the first example :smiley:

**Comment by GiggleLiu** [comment]
> Regarding two examples! Breaking into two smaller examples makes it easier to _highlight_ I thought? Although if you still want to, I can remove the first example smiley

I think making things concise is also important. As long as they serve for the same purpose, one is enough. I think removing the first one would be perfect.

**Comment by VarLad** [comment]
Looks good now? :eyes:

**Comment by GiggleLiu** [comment]
perfect, thanks!

**Pull request merged**
